config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  get '/upload', to: 'images#new'
  resources :images, only: [:index, :show, :create]

  get '/@:username', to: 'users#show', as: :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :images

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.order(created_at: :desc).limit(30)
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.build(image_params)
     if @image.save
    redirect_to @image, notice: 'Image uploaded!'
    else
      render :new
    end
  end

  private

  def image_params
    params.require(:image).permit(:image, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @images = @user.images.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<h2>Recent</h2>

<%= render "shared/images", images: @images %>

app/views/images/new.html.erb
<h2>Upload</h2>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for @image do |f| %>
      <% if f.object.errors.any? %>
        <div class="alert alert-danger">
          <p>The following errors prevent the image from being uploaded.</p>

          <ul>
            <% f.object.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.drag_and_drop_file_field :image, 'Drag and drop image here' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <%= f.submit 'Post', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<script>
  (function() {
    var reader = new FileReader()
    var form = document.querySelector('#new_image')
    var field = document.querySelector('#image_image')
    var preview = document.querySelector('#asdndz-image_image')

    reader.onload = function(e) {
      preview.style.backgroundImage = `url(${e.srcElement.result})`
    }

    field.addEventListener('dnd-upload:initialize', function(e) {
      reader.readAsDataURL(e.detail.file)
    }, false)

    form.addEventListener('click', function(e) {
      if (event.target.dataset.dndDelete === 'true') {
        preview.style.backgroundImage = ''
      }
    }, true)
  })()
</script>

app/views/images/show.html.erb
<h2>Image</h2>

<div class="row">
  <div class="col-md-9">
    <div class="card">
      <div class="card-body p-2">
        <%= image_tag @image.image, class: 'd-block w-100' %>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <%= link_to @image.user.full_name, profile_path(@image.user.username) %>

    <p class="border-top mt-3 py-2">
      <% if @image.description.present? %>
        <%= @image.description %> -
      <% end %>
      <span class="text-muted"><%= time_ago_in_words @image.created_at %> ago</span>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-lg bg-dark navbar-dark mb-3">
      <div class="container">
        <%= link_to "InstaTon", root_path, class: 'navbar-brand' %>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Recent", images_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Upload", upload_path, class: 'btn btn-primary' %>
          </li>
        </ul>


        <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.full_name, profile_path(current_user.username), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, class: 'nav-link', method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Create an Account", new_user_registration_path, class: 'btn btn-primary' %>
            </li>
          <% end %>
        </li>
      </ul>


      </div>
    </div>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h2> INsta</h2>

app/views/shared/_images.html.erb
<div class="card-columns">
  <% images.each do |image| %>
  <div class="card">
    <div class="card-body p-1">
      <%= image_tag image.image, class: 'd-block w-100 mb-1' %>
      <%= link_to "View Image", image_path(image.id), class: 'btn btn-secondary stretched-link' %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2><%= @user.full_name %></h2>

<%= render 'shared/images', images: @images %>